### ISSUE TITLE
Failed to execute 'set' on 'StylePropertyMap': Invalid propertyName: contain-intrinsic-size

### ISSUE THREAD

**Issue by mstosio** [typeofweb/typeofweb.com#163]
## Environment
- **URL**: https://typeofweb.com/
- **Browser**: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- **OS**: Google Inc. /  / Linux x86_64

## Error details
```
https://typeofweb.com/contentVisibility.min.js:0:0
Failed to execute 'set' on 'StylePropertyMap': Invalid propertyName: contain-intrinsic-size


TypeError: Failed to execute 'set' on 'StylePropertyMap': Invalid propertyName: contain-intrinsic-size
    at n (https://typeofweb.com/contentVisibility.min.js:1:364)
    at https://typeofweb.com/contentVisibility.min.js:1:587
    at Array.forEach (<anonymous>)
    at ResizeObserver.<anonymous> (https://typeofweb.com/contentVisibility.min.js:1:574)
```

**Comment by mmiszy** [comment]
@allcontributors please add @mstosio  for bug
